// Serialized into the iframe. Cycle a shuffled bag per clan: no repeats until exhausted.
// picker(clan, english, mode): mode 'self' = el héroe se ha matado solo (frases de tropezón).
export function createDeathQuipPicker() {
  var lines = {
    guerreros: [['¡Mi armadura estaba en garantía!', '¡Que alguien recoja mi honor del suelo!', 'Era una retirada táctica… demasiado vertical.', '¡Exijo revancha después de la siesta!', 'Mi espada pesa menos que mi orgullo… y aun así caí.', '¡Que conste que me dejé ganar!', 'Pensaba que el escudo se llevaba por delante.'], ['My armour was under warranty!', 'Someone pick my honour off the floor!', 'A tactical retreat… straight down.', 'Rematch after my nap!', 'My sword weighs less than my pride… and I still fell.', 'For the record, I let you win!', 'I thought the shield went in front.']],
    druidas: [['¡Me habéis podado demasiado!', 'Vuelvo al bosque… en formato abono.', '¡Regad mis raíces mientras no estoy!', 'Esto no era lo que entendía por echar raíces.', 'Me han talado el buen rollo.', '¡Plantadme en un sitio más tranquilo!', 'Solo era una fase… de la luna.'], ['You pruned me too far!', 'Back to the forest… as compost.', 'Water my roots while I am gone!', 'Not how I meant to put down roots.', 'You chopped my good vibes.', 'Plant me somewhere quieter!', 'It was just a phase… of the moon.']],
    nomuertos: [['¿Otra vez? ¡Acababa de resucitar!', '¡Guardadme el sitio en la cripta!', 'Esto ya empieza a ser una costumbre.', '¡Ni muerto me dejáis descansar!', 'Me quedé sin huesos que perder.', 'Mi médico dijo que ya no podía empeorar.', '¡Pedid la baja por defunción… otra vez!'], ['Again? I just came back!', 'Save my spot in the crypt!', 'This is becoming a habit.', 'You will not even let me rest in peace!', 'I ran out of bones to lose.', 'My doctor said I could not get worse.', 'File the death paperwork… again!']],
    vaqueros: [['Este duelo no venía en el contrato.', '¡Decidle a mi nave que la quise!', 'Me voy al gran saloon de las estrellas.', '¡Maldita sea, llevaba el láser en seguro!', 'Yo desenfundé primero… en mi imaginación.', '¡Mi sombrero era lo único que valía la pena!', 'Quién me mandaría a mí venir a este planeta…'], ['This duel was not in my contract.', 'Tell my spaceship I loved her!', 'Off to the great saloon in the stars.', 'Blast! My laser safety was on!', 'I drew first… in my imagination.', 'My hat was the only thing worth saving!', 'Why did I ever come to this planet…']],
    cotidianos: [['¡Y mañana tenía que madrugar!', 'Esto no lo cubre mi seguro.', '¡Pausa, que no había guardado partida!', '¡Decidle a mi jefe que hoy no llego!', 'Yo solo bajaba a por el pan…', '¡Tenía la lavadora puesta!', 'Lo dejo en la bandeja de pendientes.'], ['And I had an early start tomorrow!', 'My insurance does not cover this.', 'Pause! I forgot to save!', 'Tell my boss I will not make it today!', 'I was only going out for bread…', 'I left the washing machine on!', 'Adding it to my to-do list.']],
    elfos: [['¡Mi arco no estaba calibrado!', '¡Que el bosque no se entere de esto!', 'He vivido mil años para tropezar aquí.', '¡Al menos no me despeinéis las orejas!', 'Elegancia hasta el último suspiro… ¿se nota?', 'Mil años de yoga para esto.', '¡Y sin una hoja fuera de sitio!'], ['My bow was not calibrated!', 'Do not tell the forest about this!', 'A thousand years, just to trip here.', 'At least leave my ears looking elegant!', 'Elegant to the last breath… is it showing?', 'A thousand years of yoga for this.', 'And not a leaf out of place!']],
    magos: [['¡Eso no estaba en el grimorio!', 'Creo que conjuré mi propia derrota.', '¡Necesito un hechizo de garantía!', 'Me faltó maná… y me sobró confianza.', '¡Era un hechizo de teletransporte, lo juro!', 'Alguien ha tocado mis pergaminos.', 'Abracadabra… ¡vaya, esto no salía así!'], ['That was not in the spellbook!', 'I think I summoned my own defeat.', 'I need a warranty spell!', 'Too little mana… too much confidence.', 'It was a teleport spell, I swear!', 'Someone touched my scrolls.', 'Abracadabra… oh, that was not the plan!']],
    epicas: [['¡Esto no estaba en mi profecía!', 'Toda leyenda merece una segunda parte.', '¡Mi caída tendrá edición coleccionista!', 'No es el final… es el tráiler.', 'Que canten baladas sobre esto… pero editadas.', 'Mi épica caída dura menos de lo previsto.', '¡Exijo un final alternativo!'], ['This was not in my prophecy!', 'Every legend deserves a sequel.', 'My downfall gets a collector edition!', 'Not the ending… just the trailer.', 'Let them sing ballads about this… edited.', 'My epic fall was shorter than planned.', 'I demand an alternate ending!']],
    bizarros: [['¡Devolvedme al sobre, por favor!', 'Mi invocador va a oír hablar de esto.', '¡Yo solo venía a hacer un cameo!', '¡La próxima vez invocad a otro!', '¡Soy raro, no resistente!', 'Yo pensaba que esto era un sueño raro.', '¡Que alguien avise a mi fandom!'], ['Put me back in the booster, please!', 'My summoner will hear about this.', 'I was only here for a cameo!', 'Summon someone else next time!', 'I am weird, not tough!', 'I thought this was a weird dream.', 'Somebody tell my fandom!']],
    other: [['¡Esto no entraba en mis planes!', 'Me tumbo un momento… por estrategia.', '¡Que conste que casi lo tenía!', 'Volveré… cuando deje de doler.', '¿Alguien ha visto de dónde vino eso?', 'Esto lo arreglo yo con cinta americana.', 'Diré que fue un accidente laboral.'], ['This was not the plan!', 'Lying down… strategically.', 'For the record, I nearly had it!', 'I will be back… when it stops hurting.', 'Did anyone see where that came from?', 'Nothing duct tape cannot fix.', 'I will call it a workplace accident.']],
    self: [['¡Yo mismo me lo he buscado!', 'Nadie me había avisado de que el plátano era mío.', '¡Que conste que ha sido el suelo!', 'Ha sido un fuego amigo… muy amigo.', 'Me he autodesautorizado.', 'Sigue sin ser culpa mía, pero esta vez sí.', 'El suelo estaba resbaladizo, lo juro.', '¡Y yo que iba a lucirme!'], ['I did this to myself!', 'Nobody told me the banana was mine.', 'For the record, it was the floor!', 'Friendly fire… very friendly.', 'I have self-vetoed myself.', 'Still not my fault, but this time it is.', 'The floor was slippery, I swear.', 'And I was about to show off!']]
  }, bags = {}, last = {};
  return function(clan, english, mode) {
    var key = mode === 'self' ? 'self' : String(clan || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z]/g, '');
    if (!lines[key]) key = 'other';
    if (!bags[key] || !bags[key].length) {
      var bag = [];
      for (var n = 0; n < lines[key][0].length; n++) bag.push(n);
      for (var i = bag.length - 1; i > 0; i--) { var j = Math.floor(Math.random() * (i + 1)), v = bag[i]; bag[i] = bag[j]; bag[j] = v; }
      if (bag[0] === last[key]) { var first = bag[0]; bag[0] = bag[1]; bag[1] = first; }
      bags[key] = bag;
    }
    var index = bags[key].shift(); last[key] = index;
    return lines[key][english ? 1 : 0][index];
  };
}