// Parches que se inyectan en el iframe del juego, EN UN BLOQUE APARTE.
// Antes Home.jsx importaba ~180 módulos de parches (1,3 MB de texto) y viajaban dentro del bloque
// principal, retrasando el primer pintado, aunque solo se usan cuando ya se ha descargado el HTML
// del juego. Home carga este módulo con import() en paralelo con esa descarga (y main.jsx lo
// adelanta aún más, mientras se comprueba la autenticación).

import { MATCH_MODE_PATCH } from '@/lib/matchModePatch';
import { MISSION_ENGINE_PATCH, patchMissionHtml } from '@/lib/missionEnginePatch';
import { COACH_PUNKITO_PATCH } from '@/lib/coachPunkitoPatch';
import { NARRATOR_ACTION_PATCH } from '@/lib/narratorActionPatch';
import { BATTLE_UI_PATCH } from '@/lib/battleUiPatch';
import { BATTLE_PORTRAIT_PATCH } from '@/lib/battlePortraitPatch';
import { FX_ROOT_PATCH } from '@/lib/fxRootPatch';
import { COMBAT_INDICATOR_SEQUENCE_PATCH } from '@/lib/combatIndicatorSequencePatch';
import { NATIVE_INDICATOR_SEQUENCE_PATCH } from '@/lib/nativeIndicatorSequencePatch';
import { SPELL_FX_PATCH } from '@/lib/spellFxPatch';
import { ATTACK_FX_PATCH } from '@/lib/attackFxPatch';
import { SHIELD_FX_PATCH } from '@/lib/shieldFxPatch';
import { HEAL_NUMBER_PATCH } from '@/lib/healNumberPatch';
import { DAMAGE_NUMBER_PATCH } from '@/lib/damageNumberPatch';
import { MOBILE_HAPTICS_LITE_PATCH } from '@/lib/mobileHapticsLitePatch';
import { STAT_NUMBER_PATCH } from '@/lib/statNumberPatch';
import { CARD_ART_MAP_PATCH } from '@/lib/cardArtMapPatch';
import { PERF_BOOST_PATCH } from '@/lib/perfBoostPatch';
import { UUID_POLYFILL } from '@/lib/uuidPolyfill';
import { HTML_SAFETY_PATCH } from '@/lib/htmlSafetyPatch';
import { DOM_BUS_PATCH } from '@/lib/domBusPatch';
import { MATCH_EPOCH_PATCH } from '@/lib/matchEpochPatch';
import { NICK_CANON_PATCH } from '@/lib/nickCanon';
import { IMAGE_KEY_PATCH } from '@/lib/imageKeyPatch';
import { ANIM_GUARD_PATCH } from '@/lib/animGuardPatch';
import { TURN_GLIDE_PATCH } from '@/lib/turnGlidePatch';
import { END_GUARD_PATCH } from '@/lib/endGuardPatch';
import { LANG_GUARD_PATCH } from '@/lib/langGuardPatch';
import { ZOOM_FOCUS_PATCH } from '@/lib/zoomFocusPatch';
import { RESUME_PROMPT_PATCH } from '@/lib/resumePromptPatch';
import { STYLE_ORDER_PATCH } from '@/lib/styleOrderPatch';
import { MOBILE_ANTIFLICKER_PATCH } from '@/lib/mobileAntiFlickerPatch';
import { MOBILE_RESPONSIVE_PATCH } from '@/lib/mobileResponsivePatch';
import { MOBILE_PINCH_PATCH } from '@/lib/mobilePinchZoomPatch';
import { MOBILE_EXIT_PATCH } from '@/lib/mobileExitPatch';
import { MODAL_FOCUS_PATCH } from '@/lib/modalFocusPatch';
import { MOBILE_HAND_COLLAPSE_PATCH } from '@/lib/mobileHandCollapsePatch';
import { NO_FLICKER_PATCH } from '@/lib/noFlickerPatch';
import { WHITE_FLASH_FIX_PATCH } from '@/lib/whiteFlashFixPatch';
import { CRITICAL_HEAD_CSS } from '@/lib/criticalHeadCss';
import { MP_EQUIP_PATCH } from '@/lib/mpEquipPatch';
import { MP_AUCTION_PATCH } from '@/lib/mpAuctionPatch';
import { AUCTION_NODUP_PATCH } from '@/lib/auctionNoDupPatch';
import { AI_AUCTION_PATCH } from '@/lib/aiAuctionPatch';
import { HAND_UNDER_ACTION_PATCH } from '@/lib/handUnderActionPatch';
import { LOBBY_GUARD_PATCH } from '@/lib/lobbyGuardPatch';
import { EQUIP_DRAG_PATCH } from '@/lib/equipDragPatch';
import { RIVAL_HAND_BACK_PATCH } from '@/lib/rivalHandBackPatch';
import { SHOP_SPELL_ART_PATCH } from '@/lib/shopSpellArtPatch';
import { CARD_MAGNIFIER_PATCH } from '@/lib/cardMagnifierPatch';
import { HAND_DIRECT_PLAY_PATCH } from '@/lib/handDirectPlayPatch';
import { DISCARD_PILE_PATCH } from '@/lib/discardPilePatch';
import { RECOVER_SPELL_PATCH } from '@/lib/recoverSpellPatch';
import { RECOVERED_EQUIP_PATCH } from '@/lib/recoveredEquipPatch';
import { STEAL_SPELL_PATCH } from '@/lib/stealSpellPatch';
import { DRAIN_OBJECT_PATCH } from '@/lib/drainObjectPatch';
import { MP_FX_SYNC_PATCH } from '@/lib/mpFxSyncPatch';
import { SERVER_RELAY_PATCH } from '@/lib/serverRelayPatch';
import { MP_CHOICE_MODAL_PATCH } from '@/lib/mpChoiceModalPatch';
import { CENTRAL_LOBBY_PATCH } from '@/lib/centralLobbyPatch';
import { FINAL_CINEMATIC_PATCH } from '@/lib/finalCinematicPatch';
import { ODD_STATES_LOGIC_PATCH } from '@/lib/oddStatesLogicPatch';
import { STATUS_LABEL_PATCH } from '@/lib/statusLabelPatch';
import { STATUS_SCENE_FX_PATCH } from '@/lib/statusSceneFxPatch';
import { NO_HERO_MOTION_PATCH } from '@/lib/noHeroMotionPatch';
import { HERO_NAME_SIGIL_PATCH } from '@/lib/heroNameSigilPatch';
import { HERO_NAME_FIT_PATCH } from '@/lib/heroNameFitPatch';
import { RENDER_BATTLE_DEDUPE_PATCH } from '@/lib/renderBattleDedupePatch';
import { STATUS_POP_PATCH } from '@/lib/statusPopPatch';
import { CHOICE_MODAL_PATCH } from '@/lib/choiceModalPatch';
import { KILL_CINE_QUEUE_PATCH } from '@/lib/killCineQueuePatch';
import { BATTLE_ANIME_PATCH } from '@/lib/battleAnimePatch';
import { HERO_BLOOD_FX_PATCH } from '@/lib/heroBloodFxPatch';
import { MATCH_RESULT_PATCH } from '@/lib/matchResultPatch';
import { MATCH_SCORE_PATCH } from '@/lib/matchScorePatch';
import { RANKING_BUTTON_PATCH } from '@/lib/rankingButtonPatch';
import { RULES_BUTTON_PATCH } from '@/lib/rulesButtonPatch';
import { ABILITY_FX_PATCH } from '@/lib/abilityFxPatch';
import { EPIC_ABILITY_FX_PATCH } from '@/lib/epicAbilityFxPatch';
import { RAINBOW_BORDER_PATCH } from '@/lib/rainbowBorderPatch';
import { ACTION_FOCUS_PATCH } from '@/lib/actionFocusPatch';
import { ACTION_PANEL_FOCUS_PATCH } from '@/lib/actionPanelFocusPatch';
import { OBJECT_FX_PATCH } from '@/lib/objectFxPatch';
import { HAND_PICK_HIGHLIGHT_PATCH } from '@/lib/handPickHighlightPatch';
import { CARD_PLAY_REVEAL_PATCH } from '@/lib/cardPlayRevealPatch';
import { CARD_REVEAL_LOCK_PATCH } from '@/lib/cardRevealLockPatch';
import { ABILITY_USED_MEMORY_PATCH } from '@/lib/abilityUsedMemoryPatch';
import { GUIDE_HELP_BADGE_PATCH } from '@/lib/guideHelpBadgePatch';
import { SPECIAL_CARD_CINEMATIC_PATCH } from '@/lib/specialCardCinematicPatch';
import { BATTLE_RULES_PATCH } from '@/lib/battleRulesPatch';
import { buildLangEnPatch } from '@/lib/langEnPatch';
import { getLang } from '@/lib/i18n';
import { buildLangSelectorPatch } from '@/lib/langSelectorPatch';
import { NICK_REQUIRED_PATCH } from '@/lib/nickRequiredPatch';
import { NICK_MEMORY_PATCH } from '@/lib/nickMemoryPatch';
import { NICK_PASSWORD_PATCH } from '@/lib/nickPasswordPatch';
import { buildQuitContactPatch } from '@/lib/quitContactPatch';
import { HOW_TO_PLAY_PATCH } from '@/lib/howToPlayPatch';
import { DEMO_TIPS_PATCH } from '@/lib/demoTipsPatch';
import { MODE_ICON_PATCH } from '@/lib/modeIconPatch';
import { DEMO_FLOW_PATCH } from '@/lib/demoFlowPatch';
import { TYPE_MEDAL_PATCH } from '@/lib/typeMedalPatch';
import { ACTION_PANEL_STABLE_PATCH } from '@/lib/actionPanelStablePatch';
import { AI_STRATEGY_PATCH } from '@/lib/aiStrategyPatch';
import { AVATAR_PATCH } from '@/lib/avatarPatch';
import { AI_LEVEL_PATCH } from '@/lib/aiLevelPatch';
import { AI_VICTORY_CINEMATIC_PATCH } from '@/lib/aiVictoryCinematicPatch';
import { END_GAME_FIX_PATCH } from '@/lib/endGameFixPatch';
import { END_GAME_SYNC_PATCH } from '@/lib/endGameSyncPatch';
import { END_GAME_RESCUE_PATCH } from '@/lib/endGameRescuePatch';
import { END_HEROES_PATCH } from '@/lib/endHeroesPatch';
import { REMATCH_PATCH } from '@/lib/rematchPatch';
import { VS_TEXT_PATCH } from '@/lib/vsTextPatch';
import { buildFumbleRollPatch } from '@/lib/fumbleRollPatch';
import { HERO_DICE_PATCH } from '@/lib/heroDicePatch';
import { ABILITY_TARGET_FLOW_PATCH } from '@/lib/abilityTargetFlowPatch';
import { TARGET_SCOPE_PATCH } from '@/lib/targetScopePatch';
import { HERO_CARD_SPEED_PATCH } from '@/lib/heroCardSpeedPatch';
import { HERO_VEL_PATCH } from '@/lib/heroVelPatch';
import { BATTLE_SIZE_STABLE_PATCH } from '@/lib/battleSizeStablePatch';
import { PORTRAIT_PRESERVE_PATCH } from '@/lib/portraitPreservePatch';
import { HERO_FULL_FREEZE_PATCH } from '@/lib/heroFullFreezePatch';
import { BATTLE_EQUAL_SIZE_PATCH } from '@/lib/battleEqualSizePatch';
import { FOIL_SHINE_PATCH } from '@/lib/foilShinePatch';
import { THINK_BOX_SKIN_PATCH } from '@/lib/thinkBoxSkinPatch';
import { EQUIP_BADGE_BIG_PATCH } from '@/lib/equipBadgeBigPatch';
import { HERO_GEAR_CHIPS_PATCH } from '@/lib/heroGearChipsPatch';
import { ARMY_ALIGN_PATCH } from '@/lib/armyAlignPatch';
import { REARMAR_PATCH } from '@/lib/rearmarPatch';
import { DEAD_HERO_SKIP_PATCH } from '@/lib/deadHeroSkipPatch';
import { SYNC_NEW_EQUIP_PATCH } from '@/lib/syncNewEquipPatch';
import { END_GAME_WAIT_CALM_PATCH } from '@/lib/endGameWaitCalmPatch';
import { MOBILE_PORTRAIT_STILL_PATCH } from '@/lib/mobilePortraitStillPatch';
import { HUMAN_AI_EQUIP_PATCH } from '@/lib/humanAiEquipPatch';
import { buildHomeTextsPatch } from '@/lib/homeTextsPatch';
import { AUCTION_THUMB_PATCH } from '@/lib/auctionThumbPatch';
import { AUCTION_CONTROL_PATCH } from '@/lib/auctionControlPatch';
import { NARBON_ELITE_PATCH } from '@/lib/narbonElitePatch';
import { TOKEN_ABILITIES_PATCH } from '@/lib/tokenAbilitiesPatch';
import { TRANSFORM_FIX_PATCH } from '@/lib/transformFixPatch';
import { DUCK_ABILITY_PATCH } from '@/lib/duckAbilityPatch';
import { DUCK_ABSORB_FX_PATCH } from '@/lib/duckAbsorbFxPatch';
import { CRANE_SUMMON_PATCH } from '@/lib/craneSummonPatch';
import { EPIC_SUMMON_PATCH } from '@/lib/epicSummonPatch';
import { DAIDOJI_BLADE_PATCH } from '@/lib/daidojiBladePatch';
import { ABILITY_IMPL_PATCH } from '@/lib/abilityImplPatch';
import { SPELL_STEPS_PATCH } from '@/lib/spellStepsPatch';
import { REBIRTH_ABILITY_PATCH } from '@/lib/rebirthAbilityPatch';
import { DRAW_RULE_PATCH } from '@/lib/drawRulePatch';
import { BLUFF_FX_PATCH } from '@/lib/bluffFxPatch';
import { NEW_GEAR_PATCH } from '@/lib/newGearPatch';
import { INVITE_PATCH } from '@/lib/invitePatch';
import { DIAG_PATCH } from '@/lib/diagPatch';
import { STEADY_RENDER_PATCH } from '@/lib/steadyRenderPatch';
import { EQUIP_HAND_PATCH } from '@/lib/equipHandPatch';
import { RESULT_SCREEN_PATCH } from '@/lib/resultScreenPatch';
import { NIXARA_ABILITY_PATCH } from '@/lib/nixaraAbilityPatch';
import { FAST_ABILITY_PATCH } from '@/lib/fastAbilityPatch';
import { RETROPOETA_ABILITY_PATCH } from '@/lib/retropoetaAbilityPatch';
import { JUNIANA_ABILITY_PATCH } from '@/lib/junianaAbilityPatch';
import { DOJI_CONPURI_ABILITY_PATCH } from '@/lib/dojiConpuriAbilityPatch';
import { FAITHFUL_ABILITIES_PATCH } from '@/lib/faithfulAbilitiesPatch';
import { LLORILOMO_ABILITY_PATCH } from '@/lib/llorilomoAbilityPatch';
import { MONKGETA_ABILITY_PATCH } from '@/lib/monkgetaAbilityPatch';
import { RING_OBJECT_PATCH } from '@/lib/ringObjectPatch';
import { INVISIBLE_FX_PATCH } from '@/lib/invisibleFxPatch';
import { AI_EQUIP_VARIETY_PATCH } from '@/lib/aiEquipVarietyPatch';
import { AI_NEW_CARDS_PATCH } from '@/lib/aiNewCardsPatch';
import { ABILITY_TARGET_POLICY_PATCH } from '@/lib/abilityTargetPolicy';
import { patchAbilityTargetingHtml } from '@/lib/abilityTargetingHtml';
import { PASSIVE_MARKER_PATCH } from '@/lib/passiveMarkerPatch';
import { DEAD_ELITE_MARKER_PATCH, patchLivingEliteHtml } from '@/lib/deadEliteMarkerPatch';
import { ABILITY_ANIM_PATCH } from '@/lib/abilityAnimPatch';
import { TABLE_MAT_PATCH } from '@/lib/tableMatPatch';
import { EQ_HERO_SCENE_BG_PATCH } from '@/lib/eqHeroSceneBgPatch';
import { BATTLE_SCENE_BG_PATCH } from '@/lib/battleSceneBgPatch';
import { BATTLE_ART_FIX_PATCH } from '@/lib/battleArtFixPatch';
import { BATTLE_ZOOM_PATCH } from '@/lib/battleZoomPatch';
import { CHROME_PERF_PATCH } from '@/lib/chromePerfPatch';
import { TURN_UNSTICK_PATCH } from '@/lib/turnUnstickPatch';
import { STALL_GUARD_PATCH } from '@/lib/stallGuardPatch';
import { AI_WAIT_CINE_PATCH } from '@/lib/aiWaitCinePatch';
import { MP_TURN_SEQUENCE_PATCH } from '@/lib/mpTurnSequencePatch';
import { KILL_ACTOR_PATCH } from '@/lib/killActorPatch';
import { FINAL_ACTION_RECAP_PATCH } from '@/lib/finalActionRecapPatch';
import { MP_ABILITY_CINE_PATCH } from '@/lib/mpAbilityCinePatch';
import { CINE_TOGGLE_PATCH } from '@/lib/cineTogglePatch';
import { BIZARRE_ROOM_PATCH } from '@/lib/bizarreRoomPatch';
import { BIZARRE_RETURN_PATCH } from '@/lib/bizarreReturnPatch';
import { CHAT_STATUS_PATCH } from '@/lib/chatStatusPatch';
import { GAME_LOG_PATCH } from '@/lib/gameLogPatch';
import { SPEED_GAUGE_PATCH } from '@/lib/speedGaugePatch';
import { TYPE_STAT_NUMBER_PATCH } from '@/lib/typeStatNumberPatch';
import { BATTLE_LOG_ORDER_PATCH } from '@/lib/battleLogOrderPatch';
import { SKIP_REASON_LOG_PATCH } from '@/lib/skipReasonLogPatch';
import { SKIP_TURN_POP_PATCH } from '@/lib/skipTurnPopPatch';
import { HOME_MENU_PATCH } from '@/lib/homeMenuPatch';

// Variables de Home que la inyección necesita (el resto son constantes de los parches).
export function buildInject(ctx) {
  const { CONTACT_REPOSITION_PATCH, DRAGGABLE_GUIDE_PATCH, RELOAD_COVER_PATCH, IS_MOBILE, IS_PHONE, homeTexts } = ctx;
  return UUID_POLYFILL + HTML_SAFETY_PATCH + NICK_CANON_PATCH + IMAGE_KEY_PATCH + ANIM_GUARD_PATCH + TURN_GLIDE_PATCH + ZOOM_FOCUS_PATCH + DOM_BUS_PATCH + MATCH_EPOCH_PATCH + END_GUARD_PATCH + RESUME_PROMPT_PATCH + ABILITY_TARGET_POLICY_PATCH + STYLE_ORDER_PATCH + PERF_BOOST_PATCH + CHOICE_MODAL_PATCH + CONTACT_REPOSITION_PATCH + DRAGGABLE_GUIDE_PATCH + RELOAD_COVER_PATCH + MATCH_MODE_PATCH + COACH_PUNKITO_PATCH + NARRATOR_ACTION_PATCH + BATTLE_UI_PATCH + BATTLE_PORTRAIT_PATCH + FX_ROOT_PATCH + COMBAT_INDICATOR_SEQUENCE_PATCH + NATIVE_INDICATOR_SEQUENCE_PATCH + SPELL_FX_PATCH + ATTACK_FX_PATCH + SHIELD_FX_PATCH + HEAL_NUMBER_PATCH + DAMAGE_NUMBER_PATCH + STAT_NUMBER_PATCH + CARD_ART_MAP_PATCH + MP_FX_SYNC_PATCH + MP_EQUIP_PATCH + AUCTION_NODUP_PATCH + AI_AUCTION_PATCH + HAND_UNDER_ACTION_PATCH + LOBBY_GUARD_PATCH + EQUIP_DRAG_PATCH + RIVAL_HAND_BACK_PATCH + SHOP_SPELL_ART_PATCH + CARD_MAGNIFIER_PATCH + HAND_DIRECT_PLAY_PATCH + DISCARD_PILE_PATCH + SERVER_RELAY_PATCH + MP_CHOICE_MODAL_PATCH + CENTRAL_LOBBY_PATCH + FINAL_CINEMATIC_PATCH + ODD_STATES_LOGIC_PATCH + STATUS_LABEL_PATCH + STATUS_SCENE_FX_PATCH + NO_HERO_MOTION_PATCH + HERO_NAME_SIGIL_PATCH + BATTLE_ANIME_PATCH + HERO_BLOOD_FX_PATCH + MATCH_RESULT_PATCH + MATCH_SCORE_PATCH + RANKING_BUTTON_PATCH + RULES_BUTTON_PATCH + HOME_MENU_PATCH + ABILITY_FX_PATCH + EPIC_ABILITY_FX_PATCH + RAINBOW_BORDER_PATCH + ACTION_FOCUS_PATCH + ACTION_PANEL_FOCUS_PATCH + OBJECT_FX_PATCH + HAND_PICK_HIGHLIGHT_PATCH + CARD_PLAY_REVEAL_PATCH + GUIDE_HELP_BADGE_PATCH + SPECIAL_CARD_CINEMATIC_PATCH + BATTLE_RULES_PATCH + NICK_MEMORY_PATCH + NICK_PASSWORD_PATCH + NICK_REQUIRED_PATCH + buildQuitContactPatch(homeTexts) + HOW_TO_PLAY_PATCH + buildHomeTextsPatch(homeTexts) + AUCTION_THUMB_PATCH + MP_AUCTION_PATCH + AUCTION_CONTROL_PATCH + NARBON_ELITE_PATCH + TOKEN_ABILITIES_PATCH + TRANSFORM_FIX_PATCH + DUCK_ABILITY_PATCH + DUCK_ABSORB_FX_PATCH + CRANE_SUMMON_PATCH + EPIC_SUMMON_PATCH + DAIDOJI_BLADE_PATCH + ABILITY_IMPL_PATCH + SPELL_STEPS_PATCH + REBIRTH_ABILITY_PATCH + DRAW_RULE_PATCH + BLUFF_FX_PATCH + NEW_GEAR_PATCH + INVITE_PATCH + DIAG_PATCH + STEADY_RENDER_PATCH + EQUIP_HAND_PATCH + RESULT_SCREEN_PATCH + NIXARA_ABILITY_PATCH + FAST_ABILITY_PATCH + RETROPOETA_ABILITY_PATCH + JUNIANA_ABILITY_PATCH + DOJI_CONPURI_ABILITY_PATCH + FAITHFUL_ABILITIES_PATCH + LLORILOMO_ABILITY_PATCH + MONKGETA_ABILITY_PATCH + RING_OBJECT_PATCH + INVISIBLE_FX_PATCH + AI_NEW_CARDS_PATCH + ABILITY_ANIM_PATCH + PASSIVE_MARKER_PATCH + DEAD_ELITE_MARKER_PATCH + TABLE_MAT_PATCH + EQ_HERO_SCENE_BG_PATCH + BATTLE_SCENE_BG_PATCH + BATTLE_ART_FIX_PATCH + BATTLE_ZOOM_PATCH + CHROME_PERF_PATCH + TURN_UNSTICK_PATCH + STALL_GUARD_PATCH + AI_WAIT_CINE_PATCH + MP_TURN_SEQUENCE_PATCH + KILL_ACTOR_PATCH + FINAL_ACTION_RECAP_PATCH + MP_ABILITY_CINE_PATCH + CINE_TOGGLE_PATCH + BIZARRE_ROOM_PATCH + BIZARRE_RETURN_PATCH + DEMO_FLOW_PATCH + buildLangEnPatch(getLang()) + (getLang() === 'en' ? '' : LANG_GUARD_PATCH) + DEMO_TIPS_PATCH + MODE_ICON_PATCH + buildLangSelectorPatch(getLang()) + RECOVER_SPELL_PATCH + RECOVERED_EQUIP_PATCH + STEAL_SPELL_PATCH + DRAIN_OBJECT_PATCH + CHAT_STATUS_PATCH + GAME_LOG_PATCH + BATTLE_LOG_ORDER_PATCH + SKIP_REASON_LOG_PATCH + SKIP_TURN_POP_PATCH + SPEED_GAUGE_PATCH + TYPE_STAT_NUMBER_PATCH + TYPE_MEDAL_PATCH + ACTION_PANEL_STABLE_PATCH + THINK_BOX_SKIN_PATCH + EQUIP_BADGE_BIG_PATCH + AI_LEVEL_PATCH + AI_VICTORY_CINEMATIC_PATCH + AI_EQUIP_VARIETY_PATCH + AI_STRATEGY_PATCH + AVATAR_PATCH + END_GAME_FIX_PATCH + END_GAME_SYNC_PATCH + END_GAME_RESCUE_PATCH + END_HEROES_PATCH + REMATCH_PATCH + VS_TEXT_PATCH + WHITE_FLASH_FIX_PATCH + CARD_REVEAL_LOCK_PATCH + ABILITY_USED_MEMORY_PATCH + buildFumbleRollPatch(getLang()) + HERO_DICE_PATCH + ABILITY_TARGET_FLOW_PATCH + TARGET_SCOPE_PATCH + HERO_CARD_SPEED_PATCH + HERO_VEL_PATCH + BATTLE_SIZE_STABLE_PATCH + PORTRAIT_PRESERVE_PATCH + (IS_MOBILE ? MOBILE_EXIT_PATCH + NO_FLICKER_PATCH + MOBILE_ANTIFLICKER_PATCH + MOBILE_PINCH_PATCH + MODAL_FOCUS_PATCH + MOBILE_HAPTICS_LITE_PATCH : '') + MOBILE_HAND_COLLAPSE_PATCH /* también en ordenador: manos recogidas, menos repintado */ + (IS_PHONE ? MOBILE_RESPONSIVE_PATCH : '') + HERO_FULL_FREEZE_PATCH + BATTLE_EQUAL_SIZE_PATCH + FOIL_SHINE_PATCH + HERO_NAME_FIT_PATCH + STATUS_POP_PATCH + RENDER_BATTLE_DEDUPE_PATCH + KILL_CINE_QUEUE_PATCH + HERO_GEAR_CHIPS_PATCH + ARMY_ALIGN_PATCH + REARMAR_PATCH + DEAD_HERO_SKIP_PATCH + SYNC_NEW_EQUIP_PATCH + HUMAN_AI_EQUIP_PATCH + END_GAME_WAIT_CALM_PATCH + MISSION_ENGINE_PATCH + (IS_MOBILE ? MOBILE_PORTRAIT_STILL_PATCH : '');
}

// Transformaciones del HTML base del juego (antes se encadenaban en Home).
export function patchGameHtml(data) {
  return patchLivingEliteHtml(patchMissionHtml(patchAbilityTargetingHtml(data)));
}

export { CRITICAL_HEAD_CSS };
