// Texto de la guía del juego para la documentación en PDF.
export const GAME_RULES_DOC = [
  ['Objetivo', 'Forma un equipo de 3 héroes, equípalos y derrota a los 3 héroes del rival en un combate por turnos.'],
  ['Fase 1 · Subasta', 'La subasta se juega en 3 fases, una por tipo de héroe: cuerpo a cuerpo (CC), a distancia (AD) y magia (HE). En cada fase salen 6 héroes, uno por raza (cada raza con su color y símbolo). Cada jugador escribe en secreto una puja por el héroe que quiere (puja sellada, a ciegas) y, al revelarse, quien haya ofrecido más monedas se lo lleva y paga su puja. Si los dos pujan por el mismo héroe, se abre una nueva tanda de pujas. Al final de las 3 fases cada jugador tiene su equipo de 3 héroes, uno de cada tipo. Además, cada ronda trae un bonificador único que no se repite en la partida: más monedas, ventajas o un castigo al rival. Las cartas Épicas son las más poderosas, cuestan +20 monedas y solo aparecen mediante ciertos bonificadores.'],
  ['Monedas', 'Empiezas con 100 monedas de subasta y 100 de equipamiento. Si te quedas corto durante la subasta, puedes transferir monedas de tu presupuesto de equipamiento a la subasta de 10 en 10. Al acabar toda la subasta, las monedas de subasta que te sobren (si quedan) se suman a tus monedas de equipamiento, junto con los bonificadores positivos de equipamiento que te hayan salido durante la fase de subasta. Y si llegas sin monedas a la última fase, no te quedas sin tu tercer héroe: reclutas con deuda y lo que falte se resta de tu presupuesto de equipamiento.'],
  ['Fase 2 · Equipamiento', 'Cada héroe puede llevar 1 arma (cuerpo a cuerpo o a distancia) y 1 armadura; al equipar verás cómo cambian sus stats. Los hechizos son cartas únicas (solo 1 copia, gastan maná) y los objetos admiten hasta 3 copias; ambos van a tu mano para usarlos en batalla. Puedes quitar una carta comprada (×) y recuperar sus monedas.'],
  ['Fase 3 · Combate', 'Orden de turnos: distancia → hechizos → cuerpo a cuerpo (si empatan, va antes quien tenga más velocidad). En cada carta, la barra verde es la vida y la azul el maná. Acciones del héroe activo: golpe cuerpo a cuerpo (daño = CC + arma), disparo (requiere arma a distancia; daño por potencia × AD), hechizo (usa HE y gasta maná), habilidad propia del héroe, objeto de la mano, defender (recibes menos daño ese turno) o tanquear (atrae los ataques dirigidos a sus aliados). Cada acción gasta el turno. El maná es una reserva fija que no se regenera: recupéralo con el Cristal o el Orbe de Maná.'],
  ['Velocidad', 'Cada héroe lleva un marcador ⚡ + su velocidad base (el stat de su tipo: CC, AD o HE). Dentro del mismo tipo de acción, actúa antes el héroe más rápido. Los héroes más veloces (velocidad 21 o más) brillan en dorado con el sello RÁPIDO bien visible, para que sepas de un vistazo quién vuela al ficharlos y al ordenar los turnos. Algunas armas y armaduras aumentan la velocidad al equiparlas; los estados como Congelado la reducen y Dormido o Paralizado hacen perder el turno entero.'],
  ['Armaduras', 'Reducen el daño de golpes, disparos y hechizos. Las armaduras elementales anulan por completo su elemento contrario (agua-fuego, rayo-agua, hielo-rayo, fuego-hielo). La Barrera Arcana protege del daño mágico.'],
  ['Estados de combate', 'Dormido — pierde su próximo turno.\nParalizado — pierde su próximo turno.\nCongelado — actúa con velocidad reducida (va más tarde).\nMaldito — sufre una reducción temporal de atributos.\nBendito — recibe un aumento temporal de atributos.\nTanqueando — intercepta los ataques dirigidos a sus aliados hasta su próximo turno.\nConfuso — dura 2 turnos (3 en Élite) y en cada uno tiene un 50% de probabilidad de perder la acción.\nBorracho — recibe 3 de daño, pierde 3 puntos de CC, AD y HE durante 2 turnos (3 en Élite) y tiene un 35% de probabilidad de fallar su acción en cada turno afectado.\nMareado — pierde 4 puntos de CC, AD y HE durante 2 turnos (3 cuando lo provocan Gases Tóxicos en forma Élite).'],
  ['Forma Élite', 'Cuando un héroe cae por primera vez, renace en forma Élite con parte de su vida y stats mejorados según su raza (los No-muertos renacen con más). Al revivir, el héroe renace limpio: sin estados negativos (parálisis, maldición, veneno, confusión…) y sin arma ni armadura (van a la pila de descartes). Si vuelve a caer, muere definitivamente, salvo que uses Pluma Fénix (revive a un héroe) o Ave Fénix (cura a dos héroes a vida completa).'],
  ['Regla de oro de habilidades', 'Cada héroe puede usar su habilidad normal y su habilidad élite una sola vez por batalla (se cuentan por separado). Una vez jugada una, no se puede volver a usar en esa batalla, ni siquiera tras revivir en forma Élite. El botón de la habilidad ya usada se muestra atenuado y bloqueado.'],
  ['Pila de descartes', 'Cuando un héroe cae en combate, su arma y armadura van a tu pila de descartes (mazo de usados). Los objetos consumidos también van allí. La pila se muestra junto a tu mano durante la batalla, boca abajo, con un contador de cartas.'],
  ['Reanimación Arcana', 'El hechizo Reanimación Arcana (nº 117, maná 12) recupera una carta aleatoria de tu pila de descartes y la devuelve a tu mano. Si es un objeto, vuelve a ser utilizable. Si es un arma o armadura, se equipa gratis (sin coste de oro) en el héroe activo al jugarlo desde la mano. El equipo viejo del mismo tipo que tuviera el héroe va al descarte al reequiparlo.'],
  ['Modos multijugador', 'Bizarre Fantasies se puede jugar online de dos formas además de los modos local y contra la IA:\n\n• Sala privada online: creas una sala con contraseña y compartes el código con tu rival. Solo quien tenga la contraseña puede unirse. Si alguien se desconecta, la partida se puede reanudar si vuelve a entrar en 5 minutos.\n\n• Sala pública online: sala sin contraseña; cualquiera con el código puede entrar. Si alguien pierde la conexión, la partida termina sin reanudación.'],
  ['Habitación Bizarra', 'La Habitación Bizarra es un lobby público donde cualquier jugador entra con su nick y contraseña, ve quién hay dentro y puede pulsar el Botón de Pánico para ser emparejado al azar con otro visitante. Necesita un mínimo de 3 visitantes en total para activarse y tiene un máximo de 20.\n\nAl pulsar el Botón de Pánico aparece una Ruleta de la Suerte que gira entre todos los visitantes y se detiene en tu rival: la partida arranca automáticamente. Todos los que estén en la habitación ven la ruleta girar al mismo tiempo.\n\nLas partidas nacidas de la Habitación Bizarra llevan una contraseña interna (invisible para los jugadores) que permite reanudarlas si se cae la conexión. Al terminar la partida, el botón "Volver a la Habitación Bizarra" te devuelve al lobby sin pasar por el menú principal.'],
  ['Chat entre jugadores', 'Durante las partidas multijugador puedes abrir el chat desde el icono circular del borde derecho de la pantalla. El chat muestra los mensajes en tiempo real y permite enviar emojis de héroes generados por IA. Los mensajes con insultos o contenido inapropiado se bloquean automáticamente antes de enviarse. Al salir de la Habitación Bizarra, todos tus mensajes del lobby se borran automáticamente.'],
];