// Texto de la guía del juego para la documentación en PDF.
export const GAME_RULES_DOC = [
  ['Objetivo', 'Forma un equipo de 3 héroes y derrota a los 3 héroes del rival en un combate por turnos.'],
  ['Fase 1 · Subasta', 'La subasta se juega en 3 rondas, una por tipo de héroe: cuerpo a cuerpo (CC), a distancia (AD) y magia (HE). En cada ronda se muestran 6 héroes; cada jugador escribe en secreto una puja por el héroe que quiere (puja sellada, a ciegas) y, al revelarse, quien haya ofrecido más monedas se lo lleva y paga su puja. Al final de las 3 rondas cada jugador tiene su equipo de 3 héroes, uno de cada tipo. Además, cada ronda trae un bonificador único que no se repite en la partida, y las cartas Épicas cuestan +10 monedas y solo aparecen mediante ciertos bonificadores.'],
  ['Monedas', 'Empiezas con 100 monedas de subasta. Tu presupuesto de equipamiento es una base de 100 monedas más las que no gastaste en la subasta. Si te quedas corto durante la subasta, puedes transferir monedas de tu presupuesto de equipamiento a la subasta: cada moneda transferida descuenta 2 de tu presupuesto de equipamiento.'],
  ['Fase 2 · Equipamiento', 'Cada héroe puede llevar 1 arma (cuerpo a cuerpo o a distancia) y 1 armadura. Los hechizos son cartas únicas (solo 1 copia) y los objetos admiten hasta 3 copias; ambos van a tu mano para usarlos en batalla. Antes de cada compra se pide confirmación.'],
  ['Fase 3 · Combate', 'Orden de turnos: distancia → hechizos → cuerpo a cuerpo (la velocidad desempata). Acciones del héroe activo: golpe cuerpo a cuerpo, disparo (requiere arma a distancia), hechizo (gasta maná), habilidad propia, objeto de la mano, defender o tanquear (absorbe los golpes dirigidos a sus aliados). Cada acción gasta el turno. El maná es una reserva fija que no se regenera: recupéralo con Cristal u Orbe de Maná.'],
  ['Armaduras', 'Reducen el daño de golpes, disparos y hechizos. Las armaduras elementales anulan por completo su elemento contrario (agua-fuego, rayo-agua, hielo-rayo, fuego-hielo). La Barrera Arcana protege del daño mágico.'],
  ['Estados de combate', 'Dormido: pierde su próximo turno. Paralizado: pierde su próximo turno. Congelado: actúa con velocidad reducida. Maldito: sufre una reducción temporal de atributos. Bendito: recibe un aumento temporal de atributos. Tanqueando: intercepta los ataques dirigidos a sus aliados hasta su próximo turno. Confuso: dura 2 turnos (3 en Élite) y en cada uno tiene un 50% de probabilidad de perder la acción. Borracho: recibe 3 de daño, pierde 3 puntos de CC, AD y HE durante 2 turnos (3 en Élite) y tiene un 35% de probabilidad de fallar su acción en cada turno afectado.'],
  ['Forma Élite', 'Cuando un héroe cae por primera vez, renace en forma Élite con parte de su vida y stats mejorados según su raza (los No-muertos renacen con más). Si vuelve a caer, muere definitivamente, salvo que uses Pluma Fénix (revive a un héroe) o Ave Fénix (cura a dos héroes a vida completa).'],
];