// Texto de la guía del juego para la documentación en PDF.
export const GAME_RULES_DOC = [
  ['Objetivo', 'Forma un equipo de 3 héroes, equípalos y derrota a los 3 héroes del rival en un combate por turnos.'],
  ['Fase 1 · Subasta', 'La subasta se juega en 3 fases, una por tipo de héroe: cuerpo a cuerpo (CC), a distancia (AD) y magia (HE). En cada fase salen 6 héroes, uno por raza (cada raza con su color y símbolo). Cada jugador escribe en secreto una puja por el héroe que quiere (puja sellada, a ciegas) y, al revelarse, quien haya ofrecido más monedas se lo lleva y paga su puja. Si los dos pujan por el mismo héroe, se abre una nueva tanda de pujas. Al final de las 3 fases cada jugador tiene su equipo de 3 héroes, uno de cada tipo. Además, cada ronda trae un bonificador único que no se repite en la partida: más monedas, ventajas o un castigo al rival. Las cartas Épicas son las más poderosas, cuestan +20 monedas y solo aparecen mediante ciertos bonificadores.'],
  ['Monedas', 'Empiezas con 100 monedas de subasta y 100 de equipamiento. Si te quedas corto durante la subasta, puedes transferir monedas de tu presupuesto de equipamiento a la subasta de 10 en 10. Al acabar toda la subasta, las monedas de subasta que te sobren (si quedan) se suman a tus monedas de equipamiento, junto con los bonificadores positivos de equipamiento que te hayan salido durante la fase de subasta. Y si llegas sin monedas a la última fase, no te quedas sin tu tercer héroe: reclutas con deuda y lo que falte se resta de tu presupuesto de equipamiento.'],
  ['Fase 2 · Equipamiento', 'Cada héroe puede llevar 1 arma (cuerpo a cuerpo o a distancia) y 1 armadura; al equipar verás cómo cambian sus stats. Los hechizos son cartas únicas (solo 1 copia, gastan maná) y los objetos admiten hasta 3 copias; ambos van a tu mano para usarlos en batalla. Puedes quitar una carta comprada (×) y recuperar sus monedas.'],
  ['Fase 3 · Combate', 'Orden de turnos: distancia → hechizos → cuerpo a cuerpo (si empatan, va antes quien tenga más velocidad). En cada carta, la barra verde es la vida y la azul el maná. Acciones del héroe activo: golpe cuerpo a cuerpo (daño = CC + arma), disparo (requiere arma a distancia; daño por potencia × AD), hechizo (usa HE y gasta maná), habilidad propia del héroe, objeto de la mano, defender (recibes menos daño ese turno) o tanquear (atrae los ataques dirigidos a sus aliados). Cada acción gasta el turno. El maná es una reserva fija que no se regenera: recupéralo con el Cristal o el Orbe de Maná.'],
  ['Armaduras', 'Reducen el daño de golpes, disparos y hechizos. Las armaduras elementales anulan por completo su elemento contrario (agua-fuego, rayo-agua, hielo-rayo, fuego-hielo). La Barrera Arcana protege del daño mágico.'],
  ['Estados de combate', 'Dormido — pierde su próximo turno.\nParalizado — pierde su próximo turno.\nCongelado — actúa con velocidad reducida (va más tarde).\nMaldito — sufre una reducción temporal de atributos.\nBendito — recibe un aumento temporal de atributos.\nTanqueando — intercepta los ataques dirigidos a sus aliados hasta su próximo turno.\nConfuso — dura 2 turnos (3 en Élite) y en cada uno tiene un 50% de probabilidad de perder la acción.\nBorracho — recibe 3 de daño, pierde 3 puntos de CC, AD y HE durante 2 turnos (3 en Élite) y tiene un 35% de probabilidad de fallar su acción en cada turno afectado.\nMareado — pierde 4 puntos de CC, AD y HE durante 2 turnos (3 cuando lo provocan Gases Tóxicos en forma Élite).'],
  ['Forma Élite', 'Cuando un héroe cae por primera vez, renace en forma Élite con parte de su vida y stats mejorados según su raza (los No-muertos renacen con más). Si vuelve a caer, muere definitivamente, salvo que uses Pluma Fénix (revive a un héroe) o Ave Fénix (cura a dos héroes a vida completa).'],
];