// Definición de los estados de batalla: color, icono, rótulo y los DIBUJOS
// ESTÁTICOS que se reparten por la escena de batalla. Sin velos, sin filtros
// sobre el arte, sin animaciones que parpadeen: solo emojis quietos con una
// sombra suave para dar volumen.
//
// Cada partícula: t = tipo (clase CSS), e = emoji/caracter, x/y = posición,
// sz = tamaño. No hay retardo ni duración: nada se mueve.
export const STATUS_STATES = [
  {
    cls: 's-frozen', c: '#75e8ff', ic: '❄', lb: 'CONGELADO',
    decor: [
      { t: 'snowman', e: '⛄', x: '50%', y: '72%', sz: 42 },
      { t: 'santa', e: '🎅', x: '18%', y: '30%', sz: 34 },
      { t: 'icecube', e: '🧊', x: '80%', y: '78%', sz: 26 },
      { t: 'icecube', e: '🧊', x: '12%', y: '80%', sz: 22 },
      { t: 'icecube', e: '🧊', x: '70%', y: '28%', sz: 20 },
      { t: 'snowflake', e: '❄️', x: '30%', y: '16%', sz: 22 },
      { t: 'snowflake', e: '❄️', x: '88%', y: '50%', sz: 18 },
      { t: 'snowflake', e: '❄️', x: '42%', y: '90%', sz: 16 },
      { t: 'snowflake', e: '❄️', x: '8%', y: '46%', sz: 14 },
    ],
  },
  {
    cls: 's-cursed', c: '#ff45c8', ic: '☠', lb: 'MALDITO',
    decor: [
      { t: 'blackcandle', e: '🕯', x: '6%', y: '86%', sz: 20 },
      { t: 'blackcandle', e: '🕯', x: '20%', y: '92%', sz: 17 },
      { t: 'blackcandle', e: '🕯', x: '34%', y: '84%', sz: 22 },
      { t: 'blackcandle', e: '🕯', x: '48%', y: '93%', sz: 18 },
      { t: 'blackcandle', e: '🕯', x: '62%', y: '85%', sz: 21 },
      { t: 'blackcandle', e: '🕯', x: '76%', y: '92%', sz: 17 },
      { t: 'blackcandle', e: '🕯', x: '90%', y: '86%', sz: 20 },
      { t: 'voodoo', e: '🪆', x: '42%', y: '58%', sz: 24 },
      { t: 'voodoo', e: '🎎', x: '68%', y: '60%', sz: 22 },
      { t: 'voodoo', e: '🪡', x: '18%', y: '44%', sz: 18 },
      { t: 'skullrise', e: '💀', x: '26%', y: '70%', sz: 16 },
      { t: 'skullrise', e: '💀', x: '55%', y: '76%', sz: 21 },
      { t: 'skullrise', e: '💀', x: '80%', y: '72%', sz: 14 },
    ],
  },
  {
    cls: 's-paralyzed', c: '#bde8ff', ic: '⛓', lb: 'PARALIZADO',
    decor: [
      { t: 'chain', e: '⛓', x: '10%', y: '16%', sz: 20 },
      { t: 'chain', e: '⛓', x: '26%', y: '10%', sz: 24 },
      { t: 'chain', e: '⛓', x: '42%', y: '18%', sz: 21 },
      { t: 'chain', e: '⛓', x: '58%', y: '9%', sz: 25 },
      { t: 'chain', e: '⛓', x: '74%', y: '17%', sz: 21 },
      { t: 'chain', e: '⛓', x: '90%', y: '11%', sz: 23 },
      { t: 'shackle', e: '🔒', x: '9%', y: '86%', sz: 19 },
      { t: 'shackle', e: '🔒', x: '50%', y: '92%', sz: 17 },
      { t: 'shackle', e: '🔒', x: '90%', y: '86%', sz: 19 },
      { t: 'spark', e: '⚡', x: '50%', y: '44%', sz: 22 },
      { t: 'spark', e: '⚡', x: '30%', y: '68%', sz: 16 },
      { t: 'spark', e: '⚡', x: '70%', y: '72%', sz: 16 },
    ],
  },
  {
    cls: 's-sleeping', c: '#c792ff', ic: '💤', lb: 'DORMIDO',
    decor: [
      { t: 'sheep', e: '🐑', x: '14%', y: '34%', sz: 22 },
      { t: 'sheep', e: '🐑', x: '40%', y: '52%', sz: 18 },
      { t: 'sheep', e: '🐑', x: '72%', y: '74%', sz: 24 },
      { t: 'zzz', e: 'Z', x: '50%', y: '34%', sz: 22 },
      { t: 'zzz', e: 'Z', x: '58%', y: '28%', sz: 18 },
      { t: 'zzz', e: 'z', x: '66%', y: '22%', sz: 15 },
      { t: 'moon', e: '🌙', x: '14%', y: '14%', sz: 20 },
      { t: 'bear', e: '🧸', x: '12%', y: '88%', sz: 22 },
    ],
  },
  {
    cls: 's-blessed', c: '#ffe58a', ic: '✦', lb: 'BENDITO',
    decor: [
      { t: 'sparkle', e: '✨', x: '12%', y: '20%', sz: 18 },
      { t: 'sparkle', e: '✨', x: '34%', y: '12%', sz: 15 },
      { t: 'sparkle', e: '✨', x: '54%', y: '22%', sz: 20 },
      { t: 'sparkle', e: '✨', x: '76%', y: '14%', sz: 16 },
      { t: 'sparkle', e: '✨', x: '90%', y: '30%', sz: 18 },
      { t: 'sparkle', e: '✨', x: '24%', y: '80%', sz: 15 },
      { t: 'sparkle', e: '✨', x: '68%', y: '86%', sz: 18 },
      { t: 'halo', e: '👼', x: '50%', y: '54%', sz: 24 },
      { t: 'feather', e: '🪶', x: '20%', y: '5%', sz: 16 },
      { t: 'feather', e: '🪶', x: '80%', y: '5%', sz: 14 },
    ],
  },
  {
    cls: 's-tank', c: '#ffb43a', ic: '🛡', lb: 'TANQUEANDO',
    decor: [
      { t: 'shield', e: '🛡', x: '50%', y: '50%', sz: 30 },
      { t: 'shield', e: '🛡', x: '16%', y: '26%', sz: 17 },
      { t: 'shield', e: '🛡', x: '84%', y: '26%', sz: 17 },
      { t: 'shield', e: '🛡', x: '16%', y: '78%', sz: 17 },
      { t: 'shield', e: '🛡', x: '84%', y: '78%', sz: 17 },
      { t: 'clang', e: '✦', x: '34%', y: '52%', sz: 18 },
      { t: 'clang', e: '✦', x: '66%', y: '52%', sz: 18 },
    ],
  },
  {
    cls: 'bf-state-confused', c: '#ffe65a', ic: '★', lb: 'CONFUSO',
    decor: [
      { t: 'neon', e: '?', x: '14%', y: '22%', sz: 26 },
      { t: 'neon', e: '!', x: '34%', y: '14%', sz: 22 },
      { t: 'neon', e: '?', x: '56%', y: '24%', sz: 28 },
      { t: 'neon', e: '!', x: '78%', y: '13%', sz: 22 },
      { t: 'neon', e: '?', x: '92%', y: '30%', sz: 24 },
      { t: 'neon', e: '?', x: '22%', y: '78%', sz: 24 },
      { t: 'neon', e: '!', x: '48%', y: '88%', sz: 20 },
      { t: 'neon', e: '?', x: '76%', y: '80%', sz: 26 },
      { t: 'star', e: '★', x: '30%', y: '48%', sz: 20 },
      { t: 'star', e: '★', x: '70%', y: '52%', sz: 20 },
      { t: 'star', e: '★', x: '50%', y: '60%', sz: 16 },
    ],
  },
  {
    cls: 'bf-state-drunk', c: '#b8ec72', ic: '◉', lb: 'BORRACHO',
    decor: [
      { t: 'ball', e: '🪩', x: '50%', y: '42%', sz: 26 },
      { t: 'disco', e: '●', x: '10%', y: '18%', sz: 30 },
      { t: 'disco', e: '●', x: '32%', y: '12%', sz: 26 },
      { t: 'disco', e: '●', x: '54%', y: '20%', sz: 32 },
      { t: 'disco', e: '●', x: '76%', y: '13%', sz: 26 },
      { t: 'disco', e: '●', x: '92%', y: '24%', sz: 28 },
      { t: 'bubble', e: '🍺', x: '16%', y: '70%', sz: 20 },
      { t: 'bubble', e: '🫧', x: '38%', y: '76%', sz: 16 },
      { t: 'bubble', e: '🫧', x: '62%', y: '72%', sz: 18 },
      { t: 'bubble', e: '🍻', x: '86%', y: '68%', sz: 20 },
    ],
  },
  {
    cls: 'bf-state-dizzy', c: '#72f0b5', ic: '🌀', lb: 'MAREADO',
    decor: [
      { t: 'spiral', e: '🌀', x: '50%', y: '46%', sz: 30 },
      { t: 'spiral', e: '🌀', x: '18%', y: '24%', sz: 18 },
      { t: 'spiral', e: '🌀', x: '82%', y: '26%', sz: 18 },
      { t: 'spiral', e: '🌀', x: '24%', y: '78%', sz: 16 },
      { t: 'spiral', e: '🌀', x: '78%', y: '80%', sz: 16 },
      { t: 'star', e: '✦', x: '38%', y: '18%', sz: 16 },
      { t: 'star', e: '✦', x: '64%', y: '88%', sz: 16 },
      { t: 'toxic', e: '☁', x: '10%', y: '58%', sz: 22 },
      { t: 'toxic', e: '☁', x: '90%', y: '54%', sz: 22 },
    ],
  },
];