// Parches de reemplazo de texto sobre el HTML original del juego.
// Extraídos de entry.ts para mantener el archivo principal bajo el límite de
// líneas. Aplican los mismos reemplazos que antes estaban inline.
export function applyHtmlPatches(html: string, RB: string): string {
  var BTN_LEARN = RB+'843af3814_generated_image.png', BTN_RULES = RB+'0848f4ffb_generated_image.png', BTN_RACES = RB+'5e41f1add_generated_image.png';
  html = html.replace('const AD_REF=18,HE_REF=18,EQUIP_BASE=45,START_COINS=100;', 'const AD_REF=18,HE_REF=18,EQUIP_BASE=100,START_COINS=100;');
  // Batalla reordenada: campo de batalla (héroes + mano) arriba, después el
  // panel de acciones del héroe activo, luego el orden de turno y al final el registro.
  html = html.replace(
    "${ctbBar()}${actionArea}\n    <div class=\"b-grid\">${army('p')}<div class=\"vs-mid\"><span class=\"vs-txt\">VS</span></div>${army('o')}</div>",
    "<div class=\"b-grid\">${army('p')}<div class=\"vs-mid\"><span class=\"vs-txt\">VS</span></div>${army('o')}</div>\n    ${actionArea}${ctbBar()}"
  );
  html = html.replace("function roleIcon(t){return t==='CC'?'\ud83d\udde1\ufe0f':t==='AD'?'\ud83c\udff9':'\ud83d\udd2e';}", "function roleIcon(t){var E={CC:'https://media.base44.com/images/public/6a39c9aee54efe3a86d6d69a/ab147bafb_generated_image.png',AD:'https://media.base44.com/images/public/6a39c9aee54efe3a86d6d69a/fd388871c_generated_image.png',HE:'https://media.base44.com/images/public/6a39c9aee54efe3a86d6d69a/cfd5e317c_generated_image.png'};return '<img class=\"bf-role-emblem\" src=\"'+(E[t]||E.HE)+'\">';}").replace("try{ lobbyTeardown(); }catch(e){} location.reload(); }", "try{ lobbyTeardown(); }catch(e){} try{ window.top.location.href = window.top.location.pathname + '?bf=' + Date.now(); }catch(e){ location.reload(); } }").replace('onclick="startDemo()">\ud83c\udf93 Aprender a jugar</button>', 'onclick="startDemo()"><span class="tc-img"><img src="' + BTN_LEARN + '" alt=""></span><span>Aprende<br>a jugar</span></button>').replace('onclick="rulesModalStatic()">\ud83d\udcd6 C\u00f3mo se juega</button>', 'onclick="rulesModalStatic()"><span class="tc-img"><img src="' + BTN_RULES + '" alt=""></span><span>Cómo<br>se juega</span></button>').replace('onclick="racesModal()">\ud83e\uddec Razas</button>', 'onclick="racesModal()"><span class="tc-img"><img src="' + BTN_RACES + '" alt=""></span><span>Razas</span></button>').replace('<div class="coach-txt">${G._coachMsg?esc(G._coachMsg):\'\'}</div>', '<div class="coach-txt">${G._coachMsg||\'\'}</div>');
  // Re-define bonuses array, styles, logic and resolution
  html = html.replace('const BONUS=[{"id": "ban"', 'const BONUS=[{"id": "mina", "name": "Mina de Oro", "type": "PERM", "effect": 15, "txt": "+15 monedas a tu bolsa (permanente)."}, {"id": "roba", "name": "Ladrón de Guante", "type": "PERM", "effect": 15, "txt": "El rival pierde 15 monedas (permanente)."}, {"id": "ban"').replace(/"type": "BON"/g, '"type": "BID_ADD"').replace(/"type": "RES"/g, '"type": "BID_SUB"').replace(/HEROES\.filter\(h=>h\.type===['"](CC|AD|HE)['"]\)/g, "HEROES.filter(h=>h.type==='$1'&&h.clan!=='Bizarros'&&!String(h.id||'').startsWith('tk_'))");
  html = html.replace(/monedas para esta subasta/g, 'al valor de tu puja').replace(/monedas esta subasta/g, 'al valor de tu puja').replace(/monedas esta ronda/g, 'a su puja').replace('Esto es solo un ejemplo: pulsa abajo para continuar.', 'Si te quedas corto puedes transferir monedas de equipamiento a la subasta de 10 en 10. Al acabar toda la subasta, las monedas de subasta que te sobren se suman a tu presupuesto de equipamiento, junto con los bonificadores de equipamiento que te hayan salido. Esto es solo un ejemplo: pulsa abajo para continuar.').replace('PASO 2 · EQUIPAMIENTO. A cada héroe', 'PASO 2 · EQUIPAMIENTO. Tu presupuesto son 100 monedas base más lo no gastado en la subasta. A cada héroe');
  html = html.replace('function bonusChipClass(t){return t===\'BON\'?\'chip-bon\':t===\'EQP\'?\'chip-eqp\':\'chip-res\';}', 'function bonusChipClass(t){return (t===\'BID_ADD\'||t===\'PERM\')?\'chip-bon\':t===\'EQP\'?\'chip-eqp\':\'chip-res\';}');
  html = html.replace('function applyBonus(side,b){\n  if(G.pendDebt[side]){ G.coins[side]=Math.max(0,G.coins[side]-G.pendDebt[side]); G.pendDebt[side]=0; }\n  if(b.type===\'BON\'){ G.coins[side]+=b.effect; if(b.id===\'pre\')G.pendDebt[side]=8; }\n  else if(b.type===\'EQP\'){ G.equipReserve[side]+=b.effect; }\n  else if(b.type===\'RES\'){ G.coins[other(side)]=Math.max(0,G.coins[other(side)]-b.effect); }\n}', 'function applyBonus(side,b){if(G.pendDebt[side]){G.coins[side]=Math.max(0,G.coins[side]-G.pendDebt[side]);G.pendDebt[side]=0;}if(!b)return;if(b.type==="PERM"){if(b.id==="mina")G.coins[side]+=b.effect;else G.coins[other(side)]=Math.max(0,G.coins[other(side)]-b.effect);}else if(b.type==="BID_ADD"){if(b.id==="pre")G.pendDebt[side]=8;}else if(b.type==="EQP"){G.equipReserve[side]+=b.effect;}}');
  const resolveRoundOriginal = 'function resolveBidRound(){\n  const bp=G.bids.p, bo=G.bids.o; const pBid=bp&&!bp.pass, oBid=bo&&!bo.pass;\n  let contested=false, winner=null, contestId=null;\n  if(pBid && oBid && bp.heroId===bo.heroId){\n    contested=true; contestId=bp.heroId; winner=(bp.amount>=bo.amount)?\'p\':\'o\';\n    award(winner,contestId, winner===\'p\'?bp.amount:bo.amount); G.phaseNeeds[winner]=false; G.phaseNeeds[other(winner)]=true;\n  } else {\n    if(pBid){ award(\'p\',bp.heroId,bp.amount); G.phaseNeeds.p=false; }\n    if(oBid){ award(\'o\',bo.heroId,bo.amount); G.phaseNeeds.o=false; }\n  }\n  G.phaseResult={ phase:G.aIndex, sub:G.subRound, contested, winner,\n    contestName: contested?((byId(G.cands,contestId)||{}).name)||\'—\':\'\',\n    pPass:!pBid, oPass:!oBid,\n    bpName: pBid?(((byId(G.cands,bp.heroId)||{}).name)||\'—\':\'\'), boName: oBid?(((byId(G.cands,bo.heroId)||{}).name)||\'—\'):\'\',\n    bpAmt: pBid?bp.amount:0, boAmt: oBid?bo.amount:0,\n    gotP: G.phaseNeeds.p?null:nameOf(phaseHeroOf(\'p\')), gotO: G.phaseNeeds.o?null:nameOf(phaseHeroOf(\'o\')),\n    needMore: (G.phaseNeeds.p||G.phaseNeeds.o) };\n  show(\'s-recruit\'); renderRecruit(\'p\'); netSync(\'s-recruit\');\n}';
  // The bid the player sets IS the final cost (it already includes the round bonus). The winner is
  // decided by that bid directly and that exact amount is paid — the bonus is NOT re-applied here.
  const resolveRoundPatched = 'function resolveBidRound(){const bp=G.bids.p,bo=G.bids.o;const pBid=bp&&!bp.pass,oBid=bo&&!bo.pass;let contested=false,winner=null,contestId=null;if(pBid&&oBid&&bp.heroId===bo.heroId){contested=true;contestId=bp.heroId;winner=(bp.amount>=bo.amount)?"p":"o";award(winner,contestId,winner==="p"?bp.amount:bo.amount);G.phaseNeeds[winner]=false;G.phaseNeeds[other(winner)]=true;}else{if(pBid){award("p",bp.heroId,bp.amount);G.phaseNeeds.p=false;}if(oBid){award("o",bo.heroId,bo.amount);G.phaseNeeds.o=false;}}if(!pBid)G.phaseNeeds.p=false;if(!oBid)G.phaseNeeds.o=false;var fh=function(i){var c=[];if(G.epicCands){if(G.epicCands.p)c=c.concat(G.epicCands.p);if(G.epicCands.o)c=c.concat(G.epicCands.o);}if(G.cands)c=c.concat(G.cands);if(typeof HEROES!=="undefined")c=c.concat(HEROES);for(var k=0;k<c.length;k++){if(c[k]&&c[k].id===i)return c[k];}return {};};G.phaseResult={phase:G.aIndex,sub:G.subRound,contested,winner,contestName:contested?(fh(contestId).name||"—"):"",pPass:!pBid,oPass:!oBid,bpName:pBid?(fh(bp.heroId).name||"—"):"",boName:oBid?(fh(bo.heroId).name||"—"):"",bpAmt:pBid?bp.amount:0,boAmt:oBid?bo.amount:0,gotP:G.phaseNeeds.p?null:nameOf(phaseHeroOf("p")),gotO:G.phaseNeeds.o?null:nameOf(phaseHeroOf("o")),needMore:(G.phaseNeeds.p||G.phaseNeeds.o)};show("s-recruit");renderRecruit("p");netSync("s-recruit");}';
  html = html.replace(resolveRoundOriginal, resolveRoundPatched); html = html.replace('{"id": "zar", "name": "Zarmandis", "title": "Sombra del Claro", "clan": "Elfos", "clanColor": "#33aa66", "type": "AD", "cost": 16, "cc": 6, "ad": 17, "he": 5, "hp": 22, "eCc": 8, "eAd": 23, "eHe": 7, "eHp": 32, "ability": "Disparo Silencioso", "abilityTxt": "Dispara de inmediato, no puede ser bloqueado.", "eAbility": "Fantasma del Claro", "eTxt": "Dispara dos veces en silencio.", "akind": "double-ad", "weapon": "Daga Élfica"}', '{"id": "zar", "name": "Zarmanda", "title": "Sombra del Claro", "clan": "Elfos", "clanColor": "#33aa66", "type": "AD", "cost": 16, "cc": 6, "ad": 17, "he": 5, "hp": 22, "eCc": 8, "eAd": 23, "eHe": 7, "eHp": 32, "ability": "Disparo Silencioso", "abilityTxt": "Dispara de inmediato, no puede ser bloqueado.", "eAbility": "Modo Guerrera Definitiva", "eTxt": "Su pelo se eriza y brilla con un aura dorada: dispara dos veces con una fuerza descomunal digna de leyenda (aunque solo le dura el combate).", "akind": "double-ad", "weapon": "Daga Élfica"}');
  // Payment adjustment: the bid decides the winner, but bonuses DON'T count toward coins.
  // When a side wins, the coins actually deducted = bid − own adder + rival's subtractor.
  // (Own adder makes the hero cheaper to pay; rival's subtractor makes it costlier.)
  const awardOriginal = 'function award(side,heroId,amount){\n  const tmpl=byId(G.cands,heroId)||byId(HEROES,heroId);\n  G.coins[side]=Math.max(0,G.coins[side]-amount);\n  const inst=makeInstance(tmpl); inst.boughtFor=amount; G.team[side].push(inst);';
  const awardPatched = 'function award(side,heroId,amount){\n  const tmpl=byId(G.cands,heroId)||byId(HEROES,heroId);\n  var _mb=G.bonus&&G.bonus[side],_rb=G.bonus&&G.bonus[other(side)];\n  var _add=(_mb&&_mb.type==="BID_ADD")?Number(_mb.effect||0):0;\n  var _sub=(_rb&&_rb.type==="BID_SUB")?Number(_rb.effect||0):0;\n  var _paid=Math.max(0,Number(amount||0)-_add+_sub);\n  G.coins[side]=G.coins[side]-_paid;\n  const inst=makeInstance(tmpl); inst.boughtFor=_paid; G.team[side].push(inst);';
  html = html.replace(awardOriginal, awardPatched).replace('aIndex:G.aIndex, cands:G.cands, phaseResult', 'aIndex:G.aIndex, cands:G.cands, epicCands:G.epicCands, bfEquipXfer:G.bfEquipXfer, phaseResult').replace('G.cands=g.cands; G.bidsIn=g.bidsIn;', 'G.cands=g.cands; G.epicCands=g.epicCands; G.bfEquipXfer=g.bfEquipXfer||G.bfEquipXfer; G.bidsIn=g.bidsIn;');
  const recruitOriginal = '<div class="hcard-bid-zone"><input class="bid-mini-input" id="bid_${h.id}" type="number" min="0" max="${G.coins[side]}" value="${Math.min(h.cost,G.coins[side])}"><button class="btn-bid-card" onclick="submitBid(\'${side}\',\'${h.id}\')">Pujar</button></div>';
  const recruitPatched = '<div class="hcard-bid-zone" style="flex-direction:column;align-items:stretch"><div style="display:flex;gap:6px"><input style="flex:1" class="bid-mini-input" id="bid_${h.id}" type="number" min="${h.cost}" max="${G.coins[side]}" value="${Math.min(h.cost,G.coins[side])}" oninput="if(window.bfUpdateBidPreview)bfUpdateBidPreview(\'${h.id}\')"><button class="btn-bid-card" onclick="submitBid(\'${side}\',\'${h.id}\')">Pujar</button></div><div id="bidcalc_${h.id}" style="font-size:10.5px;text-align:center;line-height:1.25;margin-top:5px;font-weight:900;text-shadow:0 1px 3px #000;background:rgba(8,5,14,.6);border:1px solid rgba(255,210,74,.25);border-radius:8px;padding:4px 6px;"></div></div>';
  html = html.replace("const eqPool=BONUS.filter(b=>b.type==='EQP');\n  for(const s of ['p','o']){ const eb=pick(eqPool); G.equipReserve[s]+=eb.effect; G.bonus[s]=eb; G.equipCoins[s]=G.coins[s]+EQUIP_BASE+G.equipReserve[s]; }", "for(const s of ['p','o']){ G.equipCoins[s]=G.coins[s]+EQUIP_BASE+G.equipReserve[s]; }");
  html = html.replace(recruitOriginal, recruitPatched).replace("G.equipCoins[s]=G.coins[s]+EQUIP_BASE+G.equipReserve[s]; }", "G.equipCoins[s]=Math.max(0,G.coins[s]+EQUIP_BASE+G.equipReserve[s]-2*((G.bfEquipXfer&&G.bfEquipXfer[s])||0)); }").replace("G.equipReserve={p:0,o:0}; G.equipCoins={p:0,o:0};", "G.equipReserve={p:0,o:0}; G.equipCoins={p:0,o:0}; G.bfEquipXfer={p:0,o:0};").replace("equipReserve:{p:0,o:0}, equipCoins:{p:0,o:0},", "equipReserve:{p:0,o:0}, equipCoins:{p:0,o:0}, bfEquipXfer:{p:0,o:0},").replace('<div class="hand-lbl">Héroes</div>${acq}</div>', '<div class="coins-row" style="opacity:.85;margin-bottom:4px;width:100%"><div class="coins-num">${Math.max(0,G.coins[side]+EQUIP_BASE+G.equipReserve[side]-2*((G.bfEquipXfer&&G.bfEquipXfer[side])||0))}</div><div class="coins-lbl">monedas<br>equipamiento</div></div>${window.bfEqXferBtn(side)}<div class="hand-lbl">Héroes</div>${acq}</div>');
  // Separate Spells and Objects in battle hand and add ID to hand section so bfAddChipButtons can attach zoom, mana and cast buttons
  const hcRe = new RegExp('function handChips\\\\(side\\\\)\\\\{[\\\\s\\\\S]*?<\\\\/div>\\\\`;\\\\n\\\\}');
  html = html.replace(hcRe, 'function handChips(side){const sp=(G.spellbook[side]||[]).map(id=>{const s=byId(SPELLS,id);return "<span class=\\"chip chip-spell\\" title=\\""+esc(s.txt)+"\\">"+esc(s.name)+"</span>";}).join("")||"<span style=\\"color:#666;font-size:11px\\">—</span>";const it=(G.items[side]||[]).map(o=>"<span class=\\"chip chip-object\\" title=\\""+esc(o.txt)+"\\">"+esc(o.name)+"</span>").join("")||"<span style=\\"color:#666;font-size:11px\\">—</span>";return "<div class=\\"hand-lbl\\">Mano · Hechizos</div><div class=\\"hand-chips\\" style=\\"margin-bottom:8px\\">"+sp+"</div><div class=\\"hand-lbl\\">Mano · Objetos</div><div class=\\"hand-chips\\">"+it+"</div>";}');
  html = html.replace('<div class="hand-section"><div class="hand-lbl">Mano</div>${handChips(side)}</div>', '<div class="hand-section" id="hand_${side}">${handChips(side)}</div>');
  html = html.replace('"txt": "Revive a TODOS tus h\u00e9roes ca\u00eddos. La carta cumbre."', '"txt": "Resucita a DOS h\u00e9roes ca\u00eddos y les restaura toda la vida. La carta cumbre."').replace("case 'reviveAll':{let any=false;G.team[allies].forEach(t=>{if(!t.alive){reviveHero(t,0.5);pushFx({k:'elite',side:tSide(t),id:t.id});any=true;}});pushLog('lx',`${o.name}: ${any?'\u00a1todos reviven!':'no hab\u00eda ca\u00eddos.'}`);consume();finishAct();return;}", "case 'reviveAll':{const _d=(G.team[allies]||[]).filter(t=>!t.alive).slice(0,2);if(!_d.length){pushLog('lx',`${o.name}: no hay ca\u00eddos.`);consume();finishAct();return;}_d.forEach(t=>{reviveHero(t,1);t.hp=t.maxHp;pushFx({k:'elite',side:tSide(t),id:t.id});});pushLog('lx',`${o.name}: ${_d.map(t=>t.name).join(' y ')} ${_d.length>1?'reviven':'revive'} con vida completa.`);consume();finishAct();return;}").replace("case 'reviveAll':{let any=false;G.team[allies].forEach(t=>{if(!t.alive){reviveHero(t,0.5);any=true;}});pushLog('lx',`${o.name}: ${any?'todos reviven':'sin ca\u00eddos'}.`);break;}", "case 'reviveAll':{const _d=(G.team[allies]||[]).filter(t=>!t.alive).slice(0,2);if(_d.length){_d.forEach(t=>{reviveHero(t,1);t.hp=t.maxHp;pushFx({k:'elite',side:tSide(t),id:t.id});});pushLog('lx',`${o.name}: ${_d.map(t=>t.name).join(' y ')} ${_d.length>1?'reviven':'revive'} con vida completa.`);}else{pushLog('lx',`${o.name}: sin ca\u00eddos.`);}break;}");
  // Pacing entre turnos: el juego original avanza al siguiente turno con un
  // retardo FIJO de 400ms. Las cinemáticas grandes (habilidad 3D, kill, carta
  // especial) duran más, así que la siguiente acción empezaba mientras la
  // anterior aún se veía → solapamiento y caos en los turnos de la IA.
  // Sustituimos el setTimeout(stepTurn,400) fijo por bfStepWhenCalm(stepTurn):
  // mantiene el retardo base de 400ms (velocidad normal) pero, si hay una
  // cinemática en pantalla, espera a que termine antes de avanzar (con un
  // tope de seguridad para no colgar el juego). Sin cinemática = 400ms
  // exactos, igual que el juego original.
  html = html.replace(/setTimeout\(stepTurn,\d+\)/g, 'bfStepWhenCalm(stepTurn)');
  // BD (Oráculo) = fuente de verdad del maná de los héroes: si la carta tiene
  // maná definido en la BD, se usa ese valor como maxMana. Si no, se calcula
  // con la fórmula original (MANA_BASE[tipo] + clan.manaBonus). Así editar el
  // maná desde el backoffice se refleja en la partida.
  html = html.replace('h.maxMana=Math.max(0,(MANA_BASE[h.type]||0)+(pr.manaBonus||0)); h.mana=h.maxMana;', 'h.maxMana=(h.mana!=null&&h.mana!==""?Number(h.mana):Math.max(0,(MANA_BASE[h.type]||0)+(pr.manaBonus||0))); h.mana=h.maxMana;');
  html = html.replace(/Quita sueño\/parálisis\/maldición a un aliado\./g, 'Elimina cualquier estado negativo del héroe.');
  html = html.replace("case 'cleanse': pendTarget('Aliado a liberar',allies,(t)=>{t.sleep=0;t.para=0;t.skip=0;t._mods=t._mods.filter(m=>!(m.cc<0||m.ad<0||m.he<0));pushLog('lh',`${o.name}: ${t.name} liberado.`);consume();finishAct();});return;", "case 'cleanse': pendTarget('Héroe a restablecer',allies,(t)=>{t.sleep=0;t.para=0;t.skip=0;t.silence=0;t.mark=null;t._bfConfused=0;t._bfDrunk=0;t._mods=(t._mods||[]).filter(m=>!((m.cc||0)<0||(m.ad||0)<0||(m.he||0)<0||(m.vel||0)<0));pushLog('lh',`${o.name}: ${t.name} vuelve a su estado normal.`);consume();finishAct();});return;");
  html = html.replace("case 'cleanse':{const t=living(allies).find(a=>a.sleep||a.para||a.skip)||living(allies)[0];t.sleep=0;t.para=0;t.skip=0;pushLog('lh',`${o.name}: ${t.name} liberado.`);break;}", "case 'cleanse':{const t=living(allies).find(a=>a.sleep||a.para||a.skip||a.silence||a.mark||a._bfConfused||a._bfDrunk||(a._mods||[]).some(m=>(m.cc||0)<0||(m.ad||0)<0||(m.he||0)<0||(m.vel||0)<0))||living(allies)[0];t.sleep=0;t.para=0;t.skip=0;t.silence=0;t.mark=null;t._bfConfused=0;t._bfDrunk=0;t._mods=(t._mods||[]).filter(m=>!((m.cc||0)<0||(m.ad||0)<0||(m.he||0)<0||(m.vel||0)<0));pushLog('lh',`${o.name}: ${t.name} vuelve a su estado normal.`);break;}");
  return html;
}